[client]
showErrorDetails = "none"


[theme]

# 사용자 정의 테마가 Stramlit 기본 테마입니다
# "light" 또는 "dark" 중 하나를 선택할 수 있습니다
base = "light"

# primary color for conversation elements
primaryColor = "#027373

# background color for main contents area
backgroundColor = "#F2E7DC

# Primary Color for conversational widget in sidebar
secondaryBackgroundColor = "#A9D9D0"

# Color for most texts
textColor = "#0D0D0D"

# font family for most text except code block
# "sans serif", "serif", or "monospace" can be selected

font = "monospace"
